### ISSUE TITLE
Fix Denavit–Hartenberg parameters on iKin kinematics description files

### ISSUE THREAD

**Issue by mikearagao** [vislab-tecnico-lisboa/vizzy-yarp#7]
Edit the kinematic files to align the values with the real robot setup

**Comment by mikearagao** [comment]
@plinioMoreno as we spoke earlier I'll do this on simulation!

**Comment by mikearagao** [comment]
I'll try to close this tomorrow!

**Comment by plinioMoreno** [comment]
This is done! The head parameters seem to be good, but still need to be tested using the ball tracker
